apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db-service
    app: my-voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgres-db
  selector:
    name: postgres-pod
    app: my-voting-app