apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
    app: my-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-cache
  selector:
    name: redis-pod
    app: my-voting-app
