apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: my-voting-app
spec:
  ports:
  - port: 80
    targetPort: 80
    name: result-app-service
  selector:
    name: result-app-pod
    app: my-voting-app
  type: LoadBalancer
