apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: my-voting-app
spec:
  ports:
  - port: 80
    targetPort: 80
    name: voting-app-service
  selector:
    name: voting-app-pod
    app: my-voting-app
  type: LoadBalancer
